name:  PushToDocker
on:
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-20.04
   steps:
      - uses: actions/checkout@v2
      - run: sudo bash hack.sh
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: henloboi/docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: --force-rm --compress --no-cache --squash
          tags: "latest"
